export const CATEGORY_MAP: Record<string, { nameKey: string; sub: string[] }> = {
  "1": {
    nameKey: "smart_phone",
    sub: ["Phone", "Tablet", "Smart Watch", "Phone Accessories", "other"],
  },
  "2": {
    nameKey: "vehicles",
    sub: [
      "Car",
      "Bicycle",
      "Motorcycle",
      "Lorries",
      "Tractors",
      "Tuk Tuk & Remork",
      "Parts & Accessories",
      "Vehicles For Rent",
      "other",
    ],
  },
  "3": {
    nameKey: "beauty",
    sub: ["Skin Care", "Hair Care", "Makeup", "Natural & Organic", "other"],
  },
  "4": {
    nameKey: "furniture",
    sub: [
      "Tables & Desks",
      "Chairs & Sofas",
      "Wardrobes & Cabinets",
      "Shelves & Drawers",
      "Beds & Mattresses",
      "Curtain & Carpet",
      "Kitchenware",
      "Household Items",
      "Handicrafts-Paintings",
    ],
  },
  "5": {
    nameKey: "clothing",
    sub: [
      "Women's Fashion",
      "Men's Fashion",
      "Baby & Kids",
      "Fashion Accessories",
      "other",
    ],
  },
  "6": {
    nameKey: "computer",
    sub: [
      "Laptop",
      "Desktop",
      "All in One",
      "Monitor Printer & Scanner",
      "Parts & Accessories",
    ],
  },
  "7": {
    nameKey: "real_estates",
    sub: ["Land", "House", "Condo", "Apartment", "Commercial"],
  },
  "8": {
    nameKey: "electronic",
    sub: [
      "Washing Machines",
      "Fridges",
      "Air Conditioning",
      "Tools",
      "Machinery",
      "Security Camera",
      "TVs & Audio",
      "Video games",
      "Toys",
    ],
  },
};

export const PROVINCES = [
  "All Cambodia",
  "Phnom Penh",
  "Siem Reap",
  "Sihanoukville",
  "Battambang",
  "Kampot",
  "Banteay Meanchey",
  "Kampong Cham",
  "Kampong Chhnang",
  "Kampong Speu",
  "Kampong Thom",
  "Kandal",
  "Kep",
  "Koh Kong",
  "Kratié",
  "Mondulkiri",
  "Oddar Meanchey",
  "Pailin",
  "Preah Vihear",
  "Prey Veng",
  "Pursat",
  "Ratanakiri",
  "Stung Treng",
  "Svay Rieng",
  "Takéo",
  "Tbong Khmum",
];
