export const POST_FIELDS_MAP: Record<string, any[]> = {
  // Category 1: Electronics & Gadgets
  Phone: [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "storage", label: "Storage" },
    { key: "ram", label: "RAM" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used", "Refurbished"],
    },
  ],
  Tablet: [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "storage", label: "Storage" },
    { key: "screenSize", label: "Screen Size (inches)", type: "number" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used", "Refurbished"],
    },
  ],
  "Smart Watch": [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "compatibility", label: "Compatibility" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Phone Accessories": [
    { key: "type", label: "Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "compatibility", label: "Compatible With" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],

  // Category 2: Vehicles
  Car: [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "year", label: "Year", type: "number", required: true },
    { key: "mileage", label: "Mileage (km)", type: "number" },
    {
      key: "fuelType",
      label: "Fuel Type",
      type: "select",
      options: ["Petrol", "Diesel", "Electric", "Hybrid"],
    },
    {
      key: "transmission",
      label: "Transmission",
      type: "select",
      options: ["Manual", "Automatic"],
    },
    { key: "color", label: "Color" },
  ],
  Bicycle: [
    { key: "type", label: "Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "frameSize", label: "Frame Size" },
    { key: "gear", label: "Gear Count", type: "number" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  Motorcycle: [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "year", label: "Year", type: "number", required: true },
    { key: "mileage", label: "Mileage (km)", type: "number" },
    { key: "engineSize", label: "Engine Size (cc)", type: "number" },
    { key: "color", label: "Color" },
  ],
  Lorries: [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "year", label: "Year", type: "number", required: true },
    { key: "mileage", label: "Mileage (km)", type: "number" },
    { key: "capacity", label: "Load Capacity (tons)", type: "number" },
    {
      key: "fuelType",
      label: "Fuel Type",
      type: "select",
      options: ["Petrol", "Diesel"],
    },
  ],
  Tractors: [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "year", label: "Year", type: "number" },
    { key: "horsepower", label: "Horsepower", type: "number" },
    { key: "hours", label: "Engine Hours", type: "number" },
  ],
  "Tuk Tuk & Remork": [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model" },
    { key: "year", label: "Year", type: "number" },
    { key: "mileage", label: "Mileage (km)", type: "number" },
    { key: "seats", label: "Number of Seats", type: "number" },
  ],
  "Parts & Accessories": [
    { key: "partType", label: "Part Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "compatibility", label: "Compatible With" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  "Vehicles For Rent": [
    { key: "vehicleType", label: "Vehicle Type", required: true },
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "year", label: "Year", type: "number" },
    { key: "dailyRate", label: "Daily Rate ($)", type: "number" },
    { key: "monthlyRate", label: "Monthly Rate ($)", type: "number" },
  ],

  // Category 3: Health & Beauty
  "Skin Care": [
    { key: "brand", label: "Brand", required: true },
    { key: "productName", label: "Product Name", required: true },
    { key: "skinType", label: "Skin Type" },
    { key: "size", label: "Size/Volume" },
    { key: "expiryDate", label: "Expiry Date" },
  ],
  "Hair Care": [
    { key: "brand", label: "Brand", required: true },
    { key: "productName", label: "Product Name", required: true },
    { key: "hairType", label: "Hair Type" },
    { key: "size", label: "Size/Volume" },
    { key: "expiryDate", label: "Expiry Date" },
  ],
  Makeup: [
    { key: "brand", label: "Brand", required: true },
    { key: "productName", label: "Product Name", required: true },
    {
      key: "category",
      label: "Category",
      type: "select",
      options: ["Lipstick", "Foundation", "Eyeshadow", "Mascara", "Other"],
    },
    { key: "shade", label: "Shade/Color" },
    { key: "expiryDate", label: "Expiry Date" },
  ],
  "Natural & Organic": [
    { key: "brand", label: "Brand", required: true },
    { key: "productName", label: "Product Name", required: true },
    { key: "ingredients", label: "Main Ingredients" },
    { key: "certification", label: "Organic Certification" },
    { key: "expiryDate", label: "Expiry Date" },
  ],

  // Category 4: Home & Garden
  "Tables & Desks": [
    { key: "material", label: "Material", required: true },
    { key: "dimensions", label: "Dimensions (L x W x H)" },
    { key: "color", label: "Color" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Chairs & Sofas": [
    { key: "material", label: "Material", required: true },
    { key: "seats", label: "Number of Seats", type: "number" },
    { key: "color", label: "Color" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Wardrobes & Cabinets": [
    { key: "material", label: "Material", required: true },
    { key: "doors", label: "Number of Doors", type: "number" },
    { key: "dimensions", label: "Dimensions (L x W x H)" },
    { key: "color", label: "Color" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Shelves & Drawers": [
    { key: "material", label: "Material", required: true },
    { key: "shelves", label: "Number of Shelves/Drawers", type: "number" },
    { key: "dimensions", label: "Dimensions (L x W x H)" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Beds & Mattresses": [
    {
      key: "size",
      label: "Size",
      required: true,
      type: "select",
      options: ["Single", "Double", "Queen", "King"],
    },
    { key: "material", label: "Material" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Curtain & Carpet": [
    {
      key: "type",
      label: "Type",
      required: true,
      type: "select",
      options: ["Curtain", "Carpet", "Rug"],
    },
    { key: "material", label: "Material" },
    { key: "dimensions", label: "Dimensions" },
    { key: "color", label: "Color" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  Kitchenware: [
    { key: "type", label: "Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "material", label: "Material" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  "Household Items": [
    { key: "type", label: "Type", required: true },
    { key: "brand", label: "Brand" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  "Handicrafts-Paintings": [
    {
      key: "type",
      label: "Type",
      required: true,
      type: "select",
      options: ["Painting", "Sculpture", "Handicraft", "Other"],
    },
    { key: "artist", label: "Artist/Creator" },
    { key: "dimensions", label: "Dimensions" },
    { key: "material", label: "Material" },
  ],

  // Category 5: Fashion
  "Women's Fashion": [
    { key: "type", label: "Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "size", label: "Size", required: true },
    { key: "color", label: "Color" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Men's Fashion": [
    { key: "type", label: "Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "size", label: "Size", required: true },
    { key: "color", label: "Color" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Baby & Kids": [
    { key: "type", label: "Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "size", label: "Size/Age Range", required: true },
    { key: "color", label: "Color" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Fashion Accessories": [
    { key: "type", label: "Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "material", label: "Material" },
    { key: "color", label: "Color" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],

  // Category 6: Computers
  Laptop: [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "processor", label: "Processor" },
    { key: "ram", label: "RAM", required: true },
    { key: "storage", label: "Storage", required: true },
    { key: "screenSize", label: "Screen Size (inches)", type: "number" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used", "Refurbished"],
    },
  ],
  Desktop: [
    { key: "brand", label: "Brand", required: true },
    { key: "processor", label: "Processor", required: true },
    { key: "ram", label: "RAM", required: true },
    { key: "storage", label: "Storage", required: true },
    { key: "graphics", label: "Graphics Card" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used", "Refurbished"],
    },
  ],
  "All in One": [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model", required: true },
    { key: "processor", label: "Processor" },
    { key: "ram", label: "RAM", required: true },
    { key: "storage", label: "Storage", required: true },
    { key: "screenSize", label: "Screen Size (inches)", type: "number" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  "Monitor Printer & Scanner": [
    {
      key: "type",
      label: "Type",
      required: true,
      type: "select",
      options: ["Monitor", "Printer", "Scanner", "All-in-One"],
    },
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model" },
    { key: "size", label: "Size/Specifications" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],

  // Category 7: Property
  Land: [
    { key: "area", label: "Area (sqm)", type: "number", required: true },
    { key: "landTitle", label: "Land Title Type" },
    { key: "location", label: "Location", required: true },
    { key: "width", label: "Width (m)", type: "number" },
    { key: "length", label: "Length (m)", type: "number" },
  ],
  House: [
    { key: "bedrooms", label: "Bedrooms", type: "number", required: true },
    { key: "bathrooms", label: "Bathrooms", type: "number", required: true },
    { key: "area", label: "Floor Area (sqm)", type: "number" },
    { key: "landSize", label: "Land Size (sqm)", type: "number" },
    { key: "floors", label: "Number of Floors", type: "number" },
    {
      key: "furnished",
      label: "Furnished",
      type: "select",
      options: ["Fully Furnished", "Semi Furnished", "Unfurnished"],
    },
  ],
  Condo: [
    { key: "bedrooms", label: "Bedrooms", type: "number", required: true },
    { key: "bathrooms", label: "Bathrooms", type: "number", required: true },
    { key: "area", label: "Floor Area (sqm)", type: "number", required: true },
    { key: "floor", label: "Floor Number", type: "number" },
    {
      key: "furnished",
      label: "Furnished",
      type: "select",
      options: ["Fully Furnished", "Semi Furnished", "Unfurnished"],
    },
  ],
  Apartment: [
    { key: "bedrooms", label: "Bedrooms", type: "number", required: true },
    { key: "bathrooms", label: "Bathrooms", type: "number", required: true },
    { key: "area", label: "Floor Area (sqm)", type: "number" },
    { key: "floor", label: "Floor Number", type: "number" },
    {
      key: "furnished",
      label: "Furnished",
      type: "select",
      options: ["Fully Furnished", "Semi Furnished", "Unfurnished"],
    },
  ],
  Commercial: [
    { key: "type", label: "Property Type", required: true },
    { key: "area", label: "Floor Area (sqm)", type: "number", required: true },
    { key: "floors", label: "Number of Floors", type: "number" },
    { key: "parking", label: "Parking Spaces", type: "number" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Renovated", "Good", "Needs Renovation"],
    },
  ],

  // Category 8: Electronics & Appliances
  "Washing Machines": [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model" },
    { key: "capacity", label: "Capacity (kg)", type: "number" },
    {
      key: "type",
      label: "Type",
      type: "select",
      options: ["Top Load", "Front Load", "Semi-Automatic"],
    },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  Fridges: [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model" },
    { key: "capacity", label: "Capacity (L)", type: "number" },
    {
      key: "type",
      label: "Type",
      type: "select",
      options: ["Single Door", "Double Door", "Side by Side"],
    },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  "Air Conditioning": [
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model" },
    { key: "btu", label: "BTU/Cooling Capacity", type: "number" },
    {
      key: "type",
      label: "Type",
      type: "select",
      options: ["Split", "Window", "Portable", "Central"],
    },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  Tools: [
    { key: "type", label: "Tool Type", required: true },
    { key: "brand", label: "Brand" },
    {
      key: "powerSource",
      label: "Power Source",
      type: "select",
      options: ["Electric", "Battery", "Manual", "Petrol"],
    },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  Machinery: [
    { key: "type", label: "Machinery Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "year", label: "Year", type: "number" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used", "Refurbished"],
    },
  ],
  "Security Camera": [
    { key: "brand", label: "Brand", required: true },
    {
      key: "type",
      label: "Type",
      type: "select",
      options: ["Indoor", "Outdoor", "Dome", "PTZ", "Bullet"],
    },
    { key: "resolution", label: "Resolution" },
    {
      key: "nightVision",
      label: "Night Vision",
      type: "select",
      options: ["Yes", "No"],
    },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  "TVs & Audio": [
    {
      key: "type",
      label: "Type",
      required: true,
      type: "select",
      options: ["TV", "Soundbar", "Speakers", "Home Theater"],
    },
    { key: "brand", label: "Brand", required: true },
    { key: "model", label: "Model" },
    { key: "size", label: "Size/Specifications" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
  "Video games": [
    {
      key: "platform",
      label: "Platform",
      required: true,
      type: "select",
      options: ["PlayStation", "Xbox", "Nintendo", "PC", "Other"],
    },
    {
      key: "type",
      label: "Type",
      required: true,
      type: "select",
      options: ["Console", "Game", "Accessory"],
    },
    { key: "title", label: "Title/Model" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],
  Toys: [
    { key: "type", label: "Type", required: true },
    { key: "brand", label: "Brand" },
    { key: "ageRange", label: "Age Range" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Like New", "Used"],
    },
  ],

  // "other" for all categories
  other: [
    { key: "itemType", label: "Item Type", required: true },
    { key: "brand", label: "Brand" },
    {
      key: "condition",
      label: "Condition",
      type: "select",
      options: ["New", "Used"],
    },
  ],
};
